#name: Antlr4 Docker Image CI
#
## controls when the workflow will run
#on:
##  triggers the workflow on push or pull request but only for the master branch
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]
#
##  allows to run this workflow manually from Actions tab
#  workflow_dispatch:
#
#jobs:
#
##single job called build
#  build:
#    runs-on: ubuntu-latest
#
##  sequence of tasks that will be executed as part of the job
#    steps:
#    - uses: actions/checkout@v2
#    - name: Build the Docker image
#      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
#    - uses: actions/checkout@master
#    - name: Publish to Registry
#      uses: elgohr/Publish-Docker-Github-Action@master
#      with:
#        name: barlinbento/antlr4.9.1-pascal
#        username: ${{ secrets.DOCKER_USERNAME }}
#        password: ${{ secrets.DOCKER_PASSWORD }}
#        tag_names: true
#        cache: true
